---
title: "Interpreting breakpoint fits"
output: 
    github_document:
       df_print: kable
       fig_width: 3
       fig_height: 3
params:
 this_dataset: ["all"]
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(dplyr)
library(ggplot2)
library(strucchange)
```


### Illustration via a few real datasets

```{r loading some real datasets, fig.dim = c(6, 24), warning=FALSE, echo = FALSE, include = FALSE, messages =FALSE}

datasets <- data.frame(
  dataset_name = c("rockies",
                   "hartland",
                   "alberta",
                   "cochise_birds",
                   "salamonie",
                   "tilden",
                   #"gainesville",
                   #"gainesville_nooutlier",
                   "portal_rats",
                   "mccoy",
                   "cranbury"),
  rtrg_code = c("rtrg_304_17",
                "rtrg_102_18",
                "rtrg_105_4",
                "rtrg_133_6",
                "rtrg_19_35",
                "rtrg_172_14",
                #"rtrg_113_25",
                #"rtrg_113_25",

                NA,
                "rtrg_63_25",
                "rtrg_26_59")
)

if(params$this_dataset != "all") {
  datasets <- datasets %>%
    filter(dataset_name == params$this_dataset)

}
all_datasets <- list()


for(i in 1:nrow(datasets)) {

  if(datasets$dataset_name[i] != "portal_rats") {

    ibd <- readRDS(paste0("C:\\Users\\diaz.renata\\Documents\\GitHub\\BBSsize\\analysis\\isd_data\\ibd_isd_bbs_", datasets$rtrg_code[i], ".Rds"))

    sv <- ibd %>%
      group_by(year) %>%
      summarize(richness = length(unique(id)),
                abundance = dplyr::n(),
                biomass = sum(ind_size),
                energy = sum(ind_b)) %>%
      ungroup() %>%
      mutate(mean_energy = energy / abundance,
             mean_mass = biomass/abundance,
             site_name = datasets$dataset_name[i])

    if(datasets$dataset_name[i] == "gainesville_nooutlier") {
      sv <- filter(sv, abundance < 3000)
    }
  } else {

    individual_rats <- portalr::summarise_individual_rodents(clean = TRUE, type = "Granivores", time = "date", length = "Longterm")

    ibd <- individual_rats %>%
      filter(year %in% c(1978:2002), !is.na(wgt), treatment == "control") %>%
      mutate(six_mo = ifelse(month > 6, .5, 0)) %>%
      mutate(year_six_mo = (year + six_mo)) %>%
      mutate(bmr = 5.69 * (wgt ^ .75)) %>%
      select(year_six_mo, species, wgt, bmr) %>%
      rename(year= year_six_mo,
             id = species,
             ind_size = wgt,
             ind_b = bmr) %>%
      mutate(id = as.character(id))


    sv <- ibd %>%
      group_by(year) %>%
      summarize(richness = length(unique(id)),
                abundance = dplyr::n(),
                biomass = sum(ind_size),
                energy = sum(ind_b)) %>%
      ungroup() %>%
      mutate(mean_energy = energy / abundance,
             mean_mass = biomass/abundance,
             site_name = datasets$dataset_name[i]) %>%
      mutate(time = row_number())

  }

  all_datasets[[i]] <- sv


}

all_datasets <- bind_rows(all_datasets)

```

```{r breakpoints fxns}
source(here::here("stories", "datasets", "fxns.R"))

```

```{r multiple datasets}

abund_mods <- list()

for(i in 1:nrow(datasets)) {
  thisdat <- subset_all_datasets(site = datasets$dataset_name[i], curr = "abundance", all_datasets = all_datasets)

  abund_mods[[i]] <- summarize_breakpoints(thisdat, fit_breakpoints(thisdat))
}

abund_mods <- dplyr::bind_rows(abund_mods)
# 
# ggplot(abund_mods, aes(time, response, color = monotonic)) +
#   geom_line() +
#   geom_point(aes(time, fitted)) +
#   facet_wrap(vars(site_name), scales = "free")



energy_mods <- list()

for(i in 1:nrow(datasets)) {
  thisdat <- subset_all_datasets(site = datasets$dataset_name[i], curr = "energy", all_datasets = all_datasets)

  energy_mods[[i]] <- summarize_breakpoints(thisdat, fit_breakpoints(thisdat))
}

energy_mods <- dplyr::bind_rows(energy_mods)
# 
# ggplot(energy_mods, aes(time, response, color = monotonic)) +
#   geom_line() +
#   geom_point(aes(time, fitted)) +
#   facet_wrap(vars(site_name), scales = "free")

all_mods <- bind_rows(energy_mods, abund_mods) %>%
  mutate(site_curr = paste0(as.character(site_name), currency)) %>%
  mutate(cap_change = cap_p_wilcox <= 0.05,
         lm_change = lm_ratio != 1,
         monotonic_word = ifelse(monotonic, "monotonic", "turns"),
         monotonic_lm_steps = ifelse(monotonic, ifelse(lm_change, "monotonic", ifelse(nbp > 0, "monotonic", "monotonic flat")), "turns"),
         monotonic_cap_steps =ifelse(monotonic, ifelse(cap_change, "monotonic", ifelse(nbp > 0, "monotonic", "monotonic flat")), "turns")) %>%
  mutate(cap_increase = ifelse(cap_change, cap_ratio > 1, FALSE),
         cap_decrease = ifelse(cap_change, cap_ratio < 1, FALSE),
         lm_increase = ifelse(lm_change, lm_ratio > 1, FALSE),
         lm_decrease =ifelse(lm_change, lm_ratio < 1, FALSE),
         lm_change_word = ifelse(lm_change, paste0(monotonic_word, " trend"), paste0(monotonic_word, " no trend")),
         lm_change_description = ifelse(lm_change, 
                                        ifelse(lm_increase, "increase",
                                               "decrease"),
                                        "no trend"),
         cap_change_word = ifelse(cap_change, paste0(monotonic_word, " change"), paste0(monotonic_word, " no change")),
         cap_change_description = ifelse(cap_change,
                                         ifelse(cap_increase, "increase", 
                                                "decrease"),
                                         "no change"))
```

```{r just some ts}

ggplot(filter(all_mods, site_name == "rockies"), aes(time, response)) +
  geom_line() +
  theme_bw() +
  facet_wrap(vars(site_curr), scales = "free_y")

rockies_lms <- filter(all_mods, site_name == "rockies")


n_lm <- lm(response ~ time, filter(rockies_lms, site_curr == "rockiesabundance"))
e_lm <-lm(response ~ time, filter(rockies_lms, site_curr == "rockiesenergy"))

rockies_lms$fitted_linear <- c(e_lm$fitted.values, n_lm$fitted.values)

ggplot(rockies_lms, aes(time, response)) +
  geom_line() +
  geom_line(aes(time, fitted_linear)) +
  facet_wrap(vars(site_curr), scales = "free_y") +
  theme_bw()


```

```{r one lm}

ggplot(filter(all_mods, site_curr == "cranburyenergy"), aes(time, response)) +
  geom_line() +
  geom_line(aes(time, fitted)) +
  theme_bw() +
  ggtitle(paste0("Cranbury (NJ) Energy; end:beginning ", round(filter(all_mods, site_curr == "cranburyenergy")$lm_ratio, 2)))

```

```{r rockies turns}

ggplot(rockies_lms, aes(time, response)) +
  geom_line() +
  geom_line(aes(time, fitted, color = monotonic_word), size = 1) +
  theme_bw() +
    facet_wrap(vars(site_curr), scales = "free_y") +
  scale_color_viridis_d(end = .5)

```
